name: notes_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ^3.10.0

isar_version: &isar_version 3.1.0 # define the version to be used

dependencies:
  anim_search_bar: ^2.0.3
  authentication_repository:
    path: packages/authentication_repository
  bloc_test: ^9.1.3
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.8.2
  equatable: ^2.0.5
  errors:
    path: packages/errors
  firebase_core: ^2.14.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  fluttertoast: ^8.2.2
  font_awesome_flutter: ^10.5.0
  formz: ^0.6.0
  formz_input:
    path: packages/formz_input
  fpdart: ^0.6.0
  go_router: ^9.0.1
  internet_connection_check_service:
    path: packages/internet_connection_check_service
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  isar: *isar_version
  isar_flutter_libs: *isar_version # contains Isar Core
  isar_storage_service:
    path: packages/isar_storage_service
  json_annotation: ^4.8.1


dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  isar_generator: *isar_version
  json_serializable: ^6.7.1
  melos: ^3.1.0
  mockito: ^5.4.2
  mocktail: ^0.3.0
  test: ^1.24.1
  
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/

  fonts:
    - family: Hero
      fonts:
        - asset: assets/fonts/Hero-Bold.ttf
          weight: 700
        - asset: assets/fonts/Hero-Regular.ttf
          weight: 400
        - asset: assets/fonts/Hero-Light.ttf
          weight: 200
