name: custom_quill
description:  A dart package with a rich set of supported formatting options

publish_to: none

environment: 
  sdk: ">=3.0.0 <4.0.0"
  flutter: ^3.10.0


dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.0
  font_awesome_flutter: ^10.5.0
  flutter_colorpicker: ^1.0.3
  flutter_keyboard_visibility: ^5.4.0
  quiver: ^3.2.1
  url_launcher: ^6.1.9
  pedantic: ^1.11.1
  characters: ^1.2.1
  diff_match_patch: ^0.4.1
  i18n_extension: ">=8.0.0 <10.0.0"
  device_info_plus: ^9.0.0
  platform: ^3.1.0
  pasteboard: ^0.2.0

dev_dependencies:
    flutter_test:
      sdk: flutter