name: isar_storage_service
description: Dart package that stores data on the device.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'

isar_version: &isar_version 3.1.0 # define the version to be used

dependencies:
  flutter:
    sdk: flutter
  isar: *isar_version
  isar_flutter_libs: *isar_version # contains Isar Core
  path_provider: ^2.0.15
  storage_api:
    path: ../storage_api

dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter
  isar_generator: *isar_version
  very_good_analysis: ^5.0.0+1
  
  