name: authentication_repository
description: Dart packages that manages user authentication

environment: 
  sdk: ">=3.0.0 <4.0.0"
  flutter: ^3.10.0

dependencies:
  cloud_firestore: ^4.7.1
  equatable: ^2.0.5
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.0
  

dev_dependencies:
  build_runner:
  firebase_auth_platform_interface: ^6.15.0
  firebase_core_platform_interface: ^4.8.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.1.4
  