// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC79DsFE9VKkkc9JuDyNoPa2ox7-_WwtAU',
    appId: '1:747852461149:web:22b203c6382f73076fc9b4',
    messagingSenderId: '747852461149',
    projectId: 'kng-notes-app-20230704',
    authDomain: 'kng-notes-app-20230704.firebaseapp.com',
    storageBucket: 'kng-notes-app-20230704.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU3_uqML7QRtHgg_LrFxf2pVXto2SEYl0',
    appId: '1:747852461149:android:f7d6ad5baea147456fc9b4',
    messagingSenderId: '747852461149',
    projectId: 'kng-notes-app-20230704',
    storageBucket: 'kng-notes-app-20230704.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLXNCLzr1Kyxw1sqWUbQhoB-ESPKGoc34',
    appId: '1:747852461149:ios:8ab97a58785acb786fc9b4',
    messagingSenderId: '747852461149',
    projectId: 'kng-notes-app-20230704',
    storageBucket: 'kng-notes-app-20230704.appspot.com',
    iosClientId:
        '747852461149-hdfbj36k4ins30l7r7pg8danunr28iff.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLXNCLzr1Kyxw1sqWUbQhoB-ESPKGoc34',
    appId: '1:747852461149:ios:a46228dfb5fb829e6fc9b4',
    messagingSenderId: '747852461149',
    projectId: 'kng-notes-app-20230704',
    storageBucket: 'kng-notes-app-20230704.appspot.com',
    iosClientId:
        '747852461149-aepg9o5v455io2b7u9i3m381kavvkdj6.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp.RunnerTests',
  );
}
